### ISSUE TITLE
IPC event pool device list must match event pool device list

### ISSUE THREAD

**Issue by zzdanowicz** [oneapi-src/level-zero-spec#102]
1. Normal event pool can get device list from the context or it might be a custom list of devices provided in API function arguments.
2. When creating IPC event pool from IPC handle, device list is taken from the context.
3. Device lists of normal event pool and IPC event pool must match, otherwise driver will run into problems. 
4. Spec should explicitly prohibit it.

**Comment by jandres742** [comment]
@zzdanowicz : should match or could it be a sub-set? Let's say that in a 4 accelerator system, the even pool is created with acc0, acc1, and acc2. Then when opening the event pool handle, we do it with a context that only has:

1.
acc1 and acc3: could the driver implicitly detect that only acc1 can access the event pool?

2.
acc1 and acc2: could the driver implicitly detect that acc0 won't have access, given doesnt belong to the context?

Maybe we could add something like this to  zeEventPoolOpenIpcHandle:

"After creation, the event pool is accessible only for the devices with which the pool was originally created that also belong to the context passed to zeEventPoolOpenIpcHandle"

**Comment by zzdanowicz** [comment]
I think they should match.  And there is very little, almost to no maneuver:
2. If the device is not in event pool device list, events from that pool cannot be used on this device. 
3. Opening IPC event pool with device list (taken from the context used to open IPC event pool), means all devices from that context are able to use events from that IPC event pool.

So if IPC context has different device list than the device list of remote event pool, then you have clear contradiction between point 1 and 2. 

4. But there are practical problems, even with the "acc1" and "acc3" scenario. In order to pass that information between processes you could quickly expend all available size of IPC opaque handle (and would just kill definition of memory layout of that opaque handle, as device lists can be variable and even include sub-devices. 
5. That stands also against L0 API explicit and precise use - all implicit work adds complexity (tracking which device can or cannot use event) at least should be considered as not needed.
6. Definition of device list is also connected to the event pool allocation directly coupled with the allocation being visible and available on that devices.
7. Most important practical reason is the memory layout (number of packets) of the single event from the event pool is connected with all devices. And using such event right now will lead to memory overruns or invalid event synchronization.

Enforcing the use the exact device list for both event pools makes them behave exactly the same without any worry, implicit works and tracking. And it will save a lot of problem in case of that unregulated use.

Adding @MichalMrozek

**Comment by jandres742** [comment]
thanks @zzdanowicz . Those are good points to have the requirement that the list of devices in the importer and exporter. Thanks.

**Comment by CaoZhongZ** [comment]
How event pool API get device list from context? The current usage mode of communication of multiple devices is through multi-process. Each context of a process contains single device, and event pool is created on that context and on that single device. While sending the IPC handle to another process, it'll open on another context which contains a different device.

**Comment by zzdanowicz** [comment]
@CaoZhongZ Contexts can have variable device list or default device list by using [https://spec.oneapi.io/level-zero/latest/core/api.html#zecontextcreateex](https://spec.oneapi.io/level-zero/latest/core/api.html#zecontextcreateex).
Also when you create event pool you can use context (and its own device list) or use explicit device list [https://spec.oneapi.io/level-zero/latest/core/api.html#zeeventpoolcreate](https://spec.oneapi.io/level-zero/latest/core/api.html#zeeventpoolcreate).
In multi-device environment or when you have root device and sub devices by explicitly specifying what devices need to be in your context and/or event pool you might run into situation that remote event pool device list does not match IPC context and through this IPC event pool device list.

Yes, it is true that in two separate processes, you will have two separate context objects pointing to device objects. But with that said, these "separate process" device objects point to the real hardware devices from two separate processes. List of devices used to create remote event pool must match device list of the IPC context/event pool. 
This is a corner case when you are using non-default device list in context or event pool. 
If you are using default context and use context for event pool creation (not explicitly specified device list at event pool creation), this specification is not affecting you.

**Comment by CaoZhongZ** [comment]
Alright, that's a lengthy logic. So I'm specifying what we do or we will do in multiple process scenario, see if any problems.

1. Because of environment variable set by launcher,  a process can see only **single** device. Match to its rank. Like MPI rank 0 saw device (AFFINITY_MASK) 0.0, rank 1 saw device 0.1, rank 2 saw 1.0, etc.
2. In order to make sure that event pool is allocated on device **NOT** on host. We do explicitly specify device list, which contains the only one device the process see. And the context is from SYCL which contains the exact device.
3. Process then sends the event pool IPC handle to each others and opens received IPC pools with the context contains the single device possessed by the process.

As long as this scenario work then we are okay.

**Comment by jandres742** [comment]
@CaoZhongZ 

> While sending the IPC handle to another process, it'll open on another context which contains a different device.

L0 driver internally sends information about the device to the other process, so it knows which one is associated with. Importer and exporter process may even use different devices. The importer process doesn't need to have visibility to the same device.

This is the same scenario for memory IPC handles., where memory is exchanged, and internally, driver knows where that memory was allocated originally.

So yes, scenario above would work. if not, please let us know.

**Comment by zzdanowicz** [comment]
@CaoZhongZ 
So the device of 2) "contains the only one device" and device of 3) "contains the single device " must match.
And this is the responsibility of applications and users (settings, scripts, environment variables) to do the match. 
You must ensure your devices are matched.

**Comment by MichalMrozek** [comment]
What needs to be avoided is using pools allocated on sub devices (which expects single tile execution), on devices that contain sub devices ( i.e. 2 tile root device), such pool wouldn't have enough space to accommodate waits & signals for 2 tile root device, as it was allocated for single tile use case. For root devices with 2 tiles, we need 2 x more spaces on event pool.

**Comment by CaoZhongZ** [comment]
> @CaoZhongZ
> So the device of 2) "contains the only one device" and device of 3) "contains the single device " must match.
> And this is the responsibility of applications and users (settings, scripts, environment variables) to do the match.
> You must ensure your devices are matched.

We are talking about if they don't. Because I specifically want two totally different devices passing information through PCIE or XeLink or CLX. Please clarify this, two different devices, one allocates event pool memory on device, the other maps the virtual address across PCIE address space to it using dmabuf/gem framework.

**Comment by CaoZhongZ** [comment]
> What needs to be avoided is using pools allocated on sub devices (which expects single tile execution), on devices that contain sub devices ( i.e. 2 tile root device), such pool wouldn't have enough space to accommodate waits & signals for 2 tile root device, as it was allocated for single tile use case. For root devices with 2 tiles, we need 2 x more spaces on event pool.

Yes, we mentally treat all sub-devices as devices. And use them in sub-device level, never mix roots and subs.

**Comment by jandres742** [comment]
> We are talking about if they don't. Because I specifically want two totally different devices passing information through PCIE or XeLink or CLX. Please clarify this, two different devices, one allocates event pool memory on device, the other maps the virtual address across PCIE address space to it using dmabuf/gem framework.

yes, this would work, as long as the two different devices are both root device handles, or both sub-device handles. What is not allowed is creating the pool with one root device and using it with a sub-device, or viceversa,.

**Comment by wdamon-intel** [comment]
Out of time for v1.7.x. Moving to v1.8.

**Comment by jandres742** [comment]
@zzdanowicz , @MichalMrozek : please review PR in https://github.com/oneapi-src/level-zero-spec/pull/219
