### ISSUE TITLE
Better names for device valid timestamps bits 

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#106]
kernelTimestampValidBits  can only be used with ze_kernel_timestamp_data_t  context  and timestampValidBits  has to be used with any device global timestamps. So, more representative names would be:

kernelTimestampValidBits -> contextTimestampValidBits
timestampValidBits -> globalTimestampValidBits   

To avoid braking backwards compatibility, alias names could be used.

**Comment by joshuaranjan** [comment]
@matcabral @aravindksg

>kernelTimestampValidBits -> contextTimestampValidBits
>timestampValidBits -> globalTimestampValidBits

Please clarify what is the assumed valid bits for "kernel global timestamp" ?
For PVC it would be the same as "contextTimestampValidBits" , based on the above renaming.
Just wondering whether it would be a little confusing to mention "kernel global timestamp" has contextTimestampValidBits.
(Or may be I am missing what is "context" and "global" in the above explanation)

Alternately, would it be ok to rename only "timestampValidBits " to deviceTimestampValidBits ?
Thanks

**Comment by matcabral** [comment]
After reviewing this more in depth, I found that "kernel global timestamp" could potentially have a different resolution/valid bits than timestamps returned by *GlobalTimeStamp(). So, this request is not valid. Will close
