### ISSUE TITLE
Device and Metrics timestamps synchronization

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/level-zero-spec#11]
New API to synchronize the device and metrics timestamps. Given that source of metrics clock can vary from the main device clock it is necessary to have mechanism to synchronize time when metrics are collected. Different devices may have different metrics source clock for different metrics types, so the API should allow metric group granularity.

`ze_result_t zetDeviceGetMetricTimestamps(ze_device_handle_t hDevice, uint64_t* globalTimestamp, uint32_t *pCount,  metric_group_handle_t *phMetricGroups, uint64_t* metricTimestamps);`

**Comment by jandres742** [comment]
@matcabral: one proposal is:

```cpp
ze_result_t zetDeviceGetMetricTimestamps(
ze_device_handle_t hDevice,
uint64_t* globalTimestamp,                             
uint32_t *pCount, 
metric_group_handle_t *phMetricGroups,
uint64_t* metricTimestamps);
```
do we want to have metricTimestamps and globalTimestamp synchronized to device or host?

**Comment by matcabral** [comment]
@jandres742 , device.

**Comment by jandres742** [comment]
@matcabral : could you check https://github.com/oneapi-src/level-zero-spec/pull/78 ?

**Comment by joshuaranjan** [comment]
Hi 
Looking at the original request at https://github.com/intel-innersource/libraries.compute.oneapi.level-zero.spec/issues/34, there were 2 requirements.
1. Get a synchronized Device (or Host) , MetricGroup timestamp
2. add extended properties (in zet_metric_group_properties_t) for the metricgroup to have "timerResolution" and "timestampValidBits"

"1" is addressed here. 
Please sahre if "2" would be addreressed in another ticket ? 
I think we need both to do the mapping.

**Comment by jandres742** [comment]
> Hi Looking at the original request at [intel-innersource/libraries.compute.oneapi.level-zero.spec#34](https://github.com/intel-innersource/libraries.compute.oneapi.level-zero.spec/issues/34), there were 2 requirements.
> 
> 1. Get a synchronized Device (or Host) , MetricGroup timestamp
> 2. add extended properties (in zet_metric_group_properties_t) for the metricgroup to have "timerResolution" and "timestampValidBits"
> 
> "1" is addressed here. Please sahre if "2" would be addreressed in another ticket ? I think we need both to do the mapping.

@joshuaranjan that was not mentioned explicitly, missed that. on which API do you think those should be returned?

**Comment by joshuaranjan** [comment]
> @joshuaranjan that was not mentioned explicitly, missed that. on which API do you think those should be returned?

"timerResolution" and "timestampValidBits" could be added as an extension structure (pNext) to [zet_metric_group_properties_t]( https://spec.oneapi.io/level-zero/latest/tools/api.html?highlight=metricgroupgetproperties#_CPPv429zet_metric_group_properties_t) .
This structure is retrieved by [zetMetricGroupGetProperties](https://spec.oneapi.io/level-zero/latest/tools/api.html?highlight=metricgroupgetproperties#zetmetricgroupgetproperties)
