### ISSUE TITLE
Modifications are required for the errors reported by zesFabricPortGetFabricErrorCounters

### ISSUE THREAD

**Issue by saik-intel** [oneapi-src/level-zero-spec#112]
As per spec 1.5 new API zesFabricPortGetFabricErrorCounters has been introduced to report ANR errors. As per API definition the errors will be reported at port level and the errors reported will be FW communication errors, FW error, Communication link failures and Communication link degrades. But as per discussion happened in jira https://jira.devtools.intel.com/browse/VLK-25632 FW communication errors, FW error are reported at subdevice level and Communication link failures, Communication link degrades are reported at port level. API is reporting errors at port level and some of the errors mentioned are actually reported at subdevice level. This needs to be modified.

**Comment by saik-intel** [comment]
hi @vaidyan1-int since fw errors are part of FabricPort API structure , that means we will update fw_error count for each port which will be duplicated the count. That means even one firmware error occured at subDevice level but we rerpresent 1 * no of ports (8) = 8 fw errors by end user in his counting.

Either spec need to update in the comment saying fw errors will be at device/subdevice level even though it is part of PORT API

**Comment by wdamon-intel** [comment]
Resolved in #144
