### ISSUE TITLE
Promote ZET_METRIC_TYPE_IP_EXP out of experimental

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#116]
Metric type ZET_METRIC_TYPE_IP_EXP has been experimental for over a year. Nowadays has clear use case and implementations so it's worth to promote it out of experimental.

**Comment by jandres742** [comment]
thanks @matcabral . Since this is an enum, and is experimental, it would be just a matter of changing the name.
@wdamon-intel : what do you think?

**Comment by matcabral** [comment]
@jandres742 , I would prefer it being part of a minor/patch update such that we can plan accordingly to update the loader and implementations.

**Comment by wdamon-intel** [comment]
Moving to minor update v1.7 to better accommodate renaming and simply user differentiation of before/after.
