### ISSUE TITLE
zet_metric_global_timestamps_resolution_exp_t wrong stype 

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#118]
struct zet_metric_global_timestamps_resolution_exp_t stype must be of type ze**t**_structure_type_t .  However, it is of type ze_structure_type_t 

https://spec.oneapi.io/level-zero/latest/tools/api.html#structzet__metric__global__timestamps__resolution__exp__t

**Comment by jandres742** [comment]
this is experimental extension, so i dont think there should be a problem changing it. @wdamon-intel , what do you think?

**Comment by wdamon-intel** [comment]
@jandres742 agreed, as an experimental extension this should be corrected.

**Comment by jandres742** [comment]
Coming in https://github.com/oneapi-src/level-zero-spec/pull/130
