### ISSUE TITLE
Incoherent documentation for build logs lifetime

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero-spec#123]
Hello,

The documentation for [zeModuleDestroy](https://spec.oneapi.io/level-zero/latest/core/api.html#zemoduledestroy) specifies:
> The application must destroy all kernel and build log handles created from the module before destroying the module itself.

But the documentation of [zeModuleBuildLogDestroy](https://spec.oneapi.io/level-zero/latest/core/api.html#zemodulebuildlogdestroy) specifies:
> This function can be called before or after [zeModuleDestroy](https://spec.oneapi.io/level-zero/latest/core/api.html#zemoduledestroy) for the associated module.

This seem conflicting to me, and I think should be addressed.

For practical purposes, which is the correct behavior?

Thanks

**Comment by jandres742** [comment]
thanks @Kerilk. Yes, those are conflicting statements. In my opinion, it should be as stated in zeModuleDestroy:

> The application must destroy all kernel and build log handles created from the module before destroying the module itself.

Since the log handle might be associated in the implementation with the module, so if the module is destroyed first, that associated is lost.

@wdamon-intel : what do you think?

**Comment by wdamon-intel** [comment]
@jandres742 agree that the documentation for `zeModuleDestroy` is correct. The documentation for `zeModuleBuildLogDestroy` should be revised to state that the function must be called prior to invoking `zeModuleDestroy` on the associated module handle.

**Comment by Kerilk** [comment]
Interesting, what about link logs? Is there any such constrain for these?

**Comment by Kerilk** [comment]
Also, I just thought about it, but [zeModuleCreate](https://spec.oneapi.io/level-zero/latest/core/api.html#zemodulecreate), if it fails, may hopefully return a log but no module. So the documentation should account for this case as well. If logs have to be freed before associated modules I think the documentation should clearly specify the condition in which a module would be associated with a log (successful module creation, are link logs associated to all the modules? in case of success or failure? etc.)

**Comment by jandres742** [comment]
yes, I think that's the main use of the build log, to see what happened when module creation failed. So yes, better to have it independent.
thanks @Kerilk for bringing this into our attention.

**Comment by jandres742** [comment]
Coming https://github.com/oneapi-src/level-zero-spec/pull/129
