### ISSUE TITLE
Detailed API descriptions appear to be generated incorrectly (example: ZES_EVENT_TYPE_FLAG_DEVICE_RESET_REQUIRED)

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#124]
Lines pointed are inverted. 

https://spec.oneapi.io/level-zero/latest/sysman/api.html?highlight=zes_event_type_flag_device_reset_required#_CPPv4N21zes_event_type_flag_t41ZES_EVENT_TYPE_FLAG_DEVICE_RESET_REQUIREDE

enumerator ZES_EVENT_TYPE_FLAG_DEVICE_RESET_REQUIRED
zesDeviceGetState() to determine the reasons for the reset).  <----

Event is triggered when the device needs to be reset (use  <---

**Comment by wdamon-intel** [comment]
This appears to be a common issue across the spec.

**Comment by matcabral** [comment]
BTW, the current description is also causing confusion. A clearer description would be:

Event is triggered when the device needs to be reset (use zesDeviceGetState() to determine the reasons **requiring device reset**)
