### ISSUE TITLE
zet_debug_regset_properties_t pNext description does not say it must be nullptr if not used

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#125]
https://spec.oneapi.io/level-zero/latest/tools/api.html?highlight=zetdebuggetregistersetproperties#zet-debug-regset-properties-t

void *pNext
[in,out][optional] pointer to extension-specific structure

**Comment by jandres742** [comment]
we need then the same as in https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=pnext#_CPPv4N14ze_base_desc_t5pNextE

const void *pNext
[in][optional] must be null or a pointer to an extension-specific structure (i.e. contains sType and pNext).

**Comment by jandres742** [comment]
@wdamon-intel : on which project would you think we should have this?

**Comment by jandres742** [comment]
Coming in https://github.com/oneapi-src/level-zero-spec/pull/128
