### ISSUE TITLE
[Sysman] Meaning of engine activity could be improved for ZES_ENGINE_GROUP_COMPUTE_ALL

### ISSUE THREAD

**Issue by joshuaranjan** [oneapi-src/level-zero-spec#126]
When engine activity is reported for ZES_ENGINE_GROUP_COMPUTE_ALL using `zesEngineGetActivity` API, it is slightly ambiguous to understand whether 
1. the activity % is the average of activity for all the individual engines
OR
2. the activity %  represents the % of time at least 1 engine was active.

Option 2 of the above is the current understanding.

The Spec could be updated to add this

**Comment by joshuaranjan** [comment]
FYI: @mraghuwa

**Comment by aravindksg** [comment]
@joshuaranjan I think the intention of the *ALL engine type is mentioned in the Sysman Prog guide: https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#operations-on-engine-groups
```
There are also products where multiple engines submit work to the same underlying accelerator hardware. The hardware will execute the work from each engine concurrently. In these cases, the execution time of each individual engine will add up to more than the execution time of the underlying accelerator hardware since each engine is only receiving a portion of the accelerator hardware. In this case, the API also provides engine groups which will measure the total execution time at the level of the hardware accelerator rather than at the level of the individual engine
```
So this means that the activity report is for when _any_ of the compute engines are active between two snapshots.

**Comment by joshuaranjan** [comment]
Thanks @aravindksg for sharing the reference (I had missed it previously).

>the activity report is for when any of the compute engines are active between two snapshots
Yes, this statement is correct and makes it clear. And the spec does seem to indicate that.

>the API also provides engine groups which will measure the total execution time at the level of 
the hardware accelerator rather than at the level of the individual engine
The "total" is usually associated with "sum", which might mean additional of invidual engines' timestamps.
So if any improvement is necessary, we could replace the current one with similar to the one you proposed.

Please suggest.
