### ISSUE TITLE
code snippets do not set pNext to null ptr when not used. 

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#131]
I think is causing confusion among users making them not set it and having code segfault. 

**1.** https://spec.oneapi.io/level-zero/latest/core/PROG.html#initialization-and-discovery
[ze_device_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-properties-t) device_properties {};
        device_properties.stype = [ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-structure-type-t);

**2.** Command Queue Groups[¶](https://spec.oneapi.io/level-zero/latest/core/PROG.html#command-queue-groups)
[ze_command_queue_group_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-command-queue-group-properties-t)* cmdqueueGroupProperties = ([ze_command_queue_group_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-command-queue-group-properties-t)*)
    allocate(cmdqueueGroupCount * sizeof([ze_command_queue_group_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-command-queue-group-properties-t)));

**3.** Sub-Device Support[¶](https://spec.oneapi.io/level-zero/latest/core/PROG.html#sub-device-support)
// Query sub-device properties.
[ze_device_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-properties-t) subdeviceProps {};
subDeviceProps.stype = [ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-structure-type-t);

**4.** Interoperability with Other APIs[¶](https://spec.oneapi.io/level-zero/latest/core/PROG.html#interoperability-with-other-apis)
[ze_module_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-module-desc-t) desc = {
    [ZE_MODULE_FORMAT_NATIVE](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-module-format-t),
    clDeviceBinarySize,  **<---- THIS WILL SEGFAULT**
    clDeviceBinary
};

**5.** Enabling/Disabling and Destruction[¶](https://spec.oneapi.io/level-zero/latest/tools/PROG.html#enabling-disabling-and-destruction)
[zet_tracer_exp_desc_t](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-tracer-exp-desc-t) tracer_desc;
    tracer_desc.stype = [ZET_STRUCTURE_TYPE_TRACER_EXP_DESC](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-structure-type-t); 

**6.** Enumeration[¶](https://spec.oneapi.io/level-zero/latest/tools/PROG.html#enumeration)
also missing stype
[zet_metric_group_properties_t](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-metric-group-properties-t) 
metricGroupProperties;  

**7.** Metric Streamer[¶](https://spec.oneapi.io/level-zero/latest/tools/PROG.html#metric-streamer)
[ze_event_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-event-desc-t)              eventDesc              = {[ZE_STRUCTURE_TYPE_EVENT_DESC](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-structure-type-t)};
[zet_metric_streamer_desc_t](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-metric-streamer-desc-t)    metricStreamerDesc     = {[ZET_STRUCTURE_TYPE_METRIC_STREAMER_DESC](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-structure-type-t)};

**8.** Metric Query[¶](https://spec.oneapi.io/level-zero/latest/tools/PROG.html#metric-query)
[ze_event_pool_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-event-pool-desc-t)          eventPoolDesc         = {[ZE_STRUCTURE_TYPE_EVENT_POOL_DESC](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-structure-type-t)};
    [ze_event_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-event-desc-t)               eventDesc             = {[ZE_STRUCTURE_TYPE_EVENT_DESC](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-structure-type-t)};
[zet_metric_query_pool_desc_t](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-metric-query-pool-desc-t)   queryPoolDesc         = {[ZET_STRUCTURE_TYPE_METRIC_QUERY_POOL_DESC](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-structure-type-t)};

**9.** Calculation[¶](https://spec.oneapi.io/level-zero/latest/tools/PROG.html#calculation)
[zet_metric_properties_t](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-metric-properties-t) metricProperties;

**10.** Device Debug Properties[¶](https://spec.oneapi.io/level-zero/latest/tools/PROG.html#device-debug-properties)
also missing stype
[zet_device_debug_properties_t](https://spec.oneapi.io/level-zero/latest/tools/api.html#zet-device-debug-properties-t) props;

**11.** https://spec.oneapi.io/level-zero/latest/tools/PROG.html#device-thread-identification
[ze_device_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-properties-t) properties {};

**12.** https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#initialization
[ze_device_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-properties-t) device_properties {}
                device_properties.stype = [ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-structure-type-t)

**13.** Device component enumeration[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#device-component-enumeration)
also missing stype
[zes_freq_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-freq-properties-t) props

**14.** Sub-device management[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#sub-device-management)
[zes_freq_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-freq-properties-t) props

**15.**  Global operations[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#global-operations)
[zes_device_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-properties-t) devProps {}
[zes_pci_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-pci-properties-t) pciProps;

**16.** Operations on power domains[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#operations-on-power-domains)
2 times
[zes_power_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-power-properties-t) props
[zes_power_limit_ext_desc_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-power-limit-ext-desc-t) * allLimits = 
twice: allocate(limitCount * sizeof([zes_power_limit_ext_desc_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-power-limit-ext-desc-t)))

**17.** Scheduler operations[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#scheduler-operations)
[zes_sched_timeout_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-sched-timeout-properties-t) props

**18.** Enabling/disabling ECC Config Dynamically[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#enabling-disabling-ecc-config-dynamically)
**This will segfault**
[zes_device_ecc_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-ecc-properties-t) props = {[ZES_DEVICE_ECC_STATE_UNAVAILABLE](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-ecc-state-t), [ZES_DEVICE_ECC_STATE_UNAVAILABLE](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-ecc-state-t), [ZES_DEVICE_ACTION_NONE](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-action-t)}
[zes_device_ecc_desc_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-ecc-desc-t) newState = [ZES_DEVICE_ECC_STATE_ENABLED](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-device-ecc-state-t)

**19.** Operations on Fabric ports[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#operations-on-fabric-ports)
**also missing stype**
[zes_fabric_port_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-fabric-port-properties-t) props

**20.** Operations on fans[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#operations-on-fans)
**also missing stype**
[zes_fan_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-fan-properties-t) fanprops

**21.** Querying RAS errors[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#querying-ras-errors)
**also missing stype**
[zes_ras_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-ras-properties-t) props

**22.** Performing Diagnostics[¶](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#performing-diagnostics)
**also missing stype**
[zes_diag_properties_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-diag-properties-t) suiteProps

**23.** Linkage Inspection[¶](https://spec.oneapi.io/level-zero/latest/core/EXT_LinkageInspection.html#linkage-inspection)
// Create a linkage inspection descriptor
[ze_linkage_inspection_ext_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-linkage-inspection-ext-desc-t) inspectDesc = {
    [ZE_LINKAGE_INSPECTION_EXT_FLAG_IMPORTS](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-linkage-inspection-ext-flags-t) | [ZE_LINKAGE_INSPECTION_EXT_FLAG_UNRESOLVABLE_IMPORTS](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-linkage-inspection-ext-flags-t) | [ZE_LINKAGE_INSPECTION_EXT_FLAG_EXPORTS](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-linkage-inspection-ext-flags-t)
};

**Comment by wdamon-intel** [comment]
Fixed in #128
