### ISSUE TITLE
Add enum for zeCommandListAppendMemAdvise to set preferred location to system memory

### ISSUE THREAD

**Issue by smilczar** [oneapi-src/level-zero-spec#133]
Currently we have the following ze_memory_advice_t enum values available to control preferred memory location:
- ZE_MEMORY_ADVICE_SET_PREFERRED_LOCATION = 2,    ///< hint that the preferred memory location is the specified device
- ZE_MEMORY_ADVICE_CLEAR_PREFERRED_LOCATION = 3,  ///< removes the affect of
ref.: https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=zecommandlistappendmemadvise#_CPPv418ze_memory_advice_t

The Set option is aimed to set preferred location to the specified device only,
which is default for KMD-migrated shared allocation for performance reasons.
As a result, currently we are unable to remove its affect other than by calling clear.
But the Clear option without calling the set option is not expected to do anything.
So we need a hint to set preferred location to system memory to change the default.

**Comment by smilczar** [comment]
Note: The KMD has already uAPI for VM ADVISE to specify preferred location
to both system or device memory, and clear the current preferred location:

{code}
struct prelim_drm_i915_gem_vm_advise {
...
	/**
	 * Attributes to apply to address range or buffer object
	 *
	 * PREFERRED_LOCATION
	 *	sets the preferred memory class and instance for this object's
	 *	backing store.  This is a hint only and not guaranteed to be
	 *	honored.  It is an error to choose a memory region that was not
	 *	part of the original set of placements for the GEM object.
	 *	If choosing a preferred location that is in conflict with the
	 *	use of ATOMIC_SYSTEM or ATOMIC_DEVICE, the atomic hint will
	 *	always be honored first.
	 *	To clear the current preferred location, specify memory class
	 *	as I915_MEMORY_CLASS_NONE.
	 */
	__u32 attribute;
..
#define PRELIM_I915_VM_ADVISE_PREFERRED_LOCATION	(PRELIM_I915_VM_ADVISE | 3)
	/** Preferred location (memory region) for object backing */
	struct prelim_drm_i915_gem_memory_class_instance region;
{code}
{code}
enum prelim_drm_i915_gem_memory_class {
	PRELIM_I915_MEMORY_CLASS_SYSTEM = 0,
	PRELIM_I915_MEMORY_CLASS_DEVICE,
	PRELIM_I915_MEMORY_CLASS_NONE = -1
};
{code}

**Comment by MichalMrozek** [comment]
Looks like a spec omission, there is not option to set preferred location to host.
We should have set/clear for host preferred location, right now it is not possible to do it via API.

**Comment by jandres742** [comment]
Thanks @MichalMrozek , @smilczar . Yes, I think we need to add it.

**Comment by smilczar** [comment]
Note: alternatively, we can have a generic Get/Set MemAccessAttribute for programmer to specify ATOMIC and SYSTEM settings as well (already discussed with Ankur).
