### ISSUE TITLE
Mention about read and write memory counters overflow condition 

### ISSUE THREAD

**Issue by mraghuwa** [oneapi-src/level-zero-spec#139]
Currently it is observed that on some platforms read and write counters tends to overflow. Mention about this behaviour in spec and also please add that the information about how to handle the overflows.

**Comment by saik-intel** [comment]
Minute of Meeting:
•	Current API is summing all HBM read and write counters and exposing the sum value to XPUM hence it is not possible to detect XPUM as L0 is summing up.
•	Two solution discussed
o	a)  FIRST proposal: L0 expose read/write counter structures for each HBM and XPUM team need to detect its overflow for each HBM.  
o	 B) Second proposal:  LO driver update api by adding extra field called duration and it will update read/write and current bandwidth in that duration window which XPUM team can consume and use it and L0 will fix the overclocks if any occurs within duration time
•	XPUM and L0 Sysman agreed with second proposal as below
o	Proposed new API interface with adding “duration”  option to the XPUM team .
o	L0 Sysman internally fix the read/write overflows of HBM counters in given duration time and expose the read/write counters at given timestamp for the duration mentioned by API and current bandwidth

**Comment by saik-intel** [comment]
@jandres742  @wdamon-intel   please assign to sanil and drive this to get fixed

**Comment by wdamon-intel** [comment]
PR #134

**Comment by wdamon-intel** [comment]
Closed with PR #134
