### ISSUE TITLE
Define spec/experimental extension discovery process for Sysman

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#149]
Currently the discovery for extensions is only via the 2 core APIs defined in : https://spec.oneapi.io/level-zero/latest/core/EXT.html
which is `zeDriverGetExtesnsionProperties` or `zeDriverGetExtensionFucttionAddress`.

Ask here is to define independent extension discovery and API evolution process for Sysman so development can be separate for Core/Sysman

**Comment by aravindksg** [comment]
@wdamon-intel @sanilkumar0 @jandres742

**Comment by wdamon-intel** [comment]
PR in #161
