### ISSUE TITLE
Add ze_device_type_t type” and “ze_device_property_flags_t flags” members to part of Sysman Device structure

### ISSUE THREAD

**Issue by saik-intel** [oneapi-src/level-zero-spec#150]
with zesInit() introduced, sysman is independent of core for getting device

As we are going to get rid of the below core structure in major version
[ze_device_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#_CPPv422ze_device_properties_t) core
[out] Core device properties

https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv423zes_device_properties_t

GeoPM uses the [ze_device_type_t](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-type-t) type” and “[ze_device_property_flags_t ](https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-property-flags-t)flags” members  from above structure. Hence we need to add these two structures part of Sysman own structure same like UUID https://github.com/oneapi-src/level-zero-spec/issues/111 

please tag it to spec1.7 update

**Comment by saik-intel** [comment]
@jandres742  please tag to spec 1.7 and make it important to update part of upcoming spec change  @wdamon-intel   please tag to spec1.8

**Comment by jandres742** [comment]
@sanilkumar0: please take a look if this can be done.
