### ISSUE TITLE
`ze_kernel_max_group_size_properties_ext_t` does not have a defined structure type

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero-spec#156]
`ze_kernel_max_group_size_properties_ext_t` does not have its type defined in `ze_structure_type_t` (should be `ZE_STRUCTURE_TYPE_KERNEL_MAX_GROUP_SIZE_PROPERTIES_EXT`)

**Comment by jandres742** [comment]
thanks @Kerilk . Actually, we have another error here: the correct suffix should be ext_properties_t. https://spec.oneapi.io/level-zero/latest/core/EXT.html#naming-convention. But we cannot change that w/o breaking compatibility. I will add the stype and think how to fix the issue with wrong naming convention.

**Comment by Kerilk** [comment]
Indeed.
I think adding a type alias would solve your issue:
`typedef ze_kernel_max_group_size_ext_properties_t ze_kernel_max_group_size_properties_ext_t;`
