### ISSUE TITLE
`ZET_STRUCTURE_TYPE_GLOBAL_METRICS_TIMESTAMPS_EXP_PROPERTIES` does not respect naming convention

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero-spec#158]
`ZET_STRUCTURE_TYPE_GLOBAL_METRICS_TIMESTAMPS_EXP_PROPERTIES` should be named `ZET_STRUCTURE_TYPE_METRIC_GLOBAL_TIMESTAMPS_RESOLUTION_EXP` to match it's structure name `zet_metric_global_timestamps_resolution_exp_t`.

**Comment by wdamon-intel** [comment]
PR #170
