### ISSUE TITLE
Timestamp unit is not specified for all Sysman metric types

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero-spec#16]
Timestamp unit / resolution is explicitly specified as microseconds for following metrics:
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-pci-stats-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-engine-stats-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-fabric-port-throughput-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-freq-throttle-time-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-power-energy-counter-t

But not for:
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-mem-bandwidth-t

Same microsecond resolution is implied by the provided bandwidth algorithm, but it should be _explicitly_ stated also for the memory bandwidth timestamp.

----

PS. Maybe there could be also some generic statement at start of the docs, about all timestamps in the Sysman API being reported as microseconds, regardless of what resolution HW actually offers for the backend.

Or is it possible that the nanoseconds and cycles mentioned in core API (https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-properties-t) could be used in Sysman API later on?

**Comment by eero-t** [comment]
Ping... IMHO clarifying this is somewhat urgent because current backend implementation returns nanoseconds, instead of microseconds implied by the spec, and both XPU Manager and collectd Sysman plugin public projects report bogus values (partially) because of that.

**Comment by jandres742** [comment]
@sanilkumar0 @saik-intel: do we want to do this for v1.6? maybe we could check if all metrics have the proper units documented.

**Comment by eero-t** [comment]
Another thing you could clarify in the spec is those example algorithms.

Both of these talk about percentages:
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-engine-stats-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-mem-bandwidth-t

But the provided engine utilization algorithm will obviously provide values in 0-1 range, not 0-100.  I would assume same to apply also to mem BW.

(Specs for rest of the metrics do not mention percentages.)

**Comment by jandres742** [comment]
@sanilkumar0 @saik-intel: could you review https://github.com/oneapi-src/level-zero-spec/pull/66 ?

**Comment by sanilkumar0** [comment]
Are all these timestamp coming from the same clock (cpu timestamp). Its good normalize on single clock and unit (microseconds) so you are talking about PCIE BW or Fabric BW, its the same resolution and units applied and easy for customer to understsand.

**Comment by jandres742** [comment]
thanks @sanilkumar0 
@saik-intel: do you know?

> Are all these timestamp coming from the same clock (cpu timestamp)

**Comment by eero-t** [comment]
All the linked spec items state that:
> Never take the delta of this timestamp with the timestamp from a different structure since they are not guaranteed to have the same base.
