### ISSUE TITLE
`zesFabricPortGetFabricErrorCounters` was removed from the loader, breaking the ABI

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero-spec#160]
This change in https://github.com/oneapi-src/level-zero/commit/4f75f9e51286370e9dcd7460ef86553f05f23014 removed the `zesFabricPortGetFabricErrorCounters` symbol from the library, thus breaking the ABI. It should have been marked deprecated.

**Comment by wdamon-intel** [comment]
Fixed in v1.7 with #144
