### ISSUE TITLE
[Sysman] update documentation of  zesSchedulerSetComputeUnitDebugMode 

### ISSUE THREAD

**Issue by saik-intel** [oneapi-src/level-zero-spec#164]
https://spec.oneapi.io/level-zero/latest/sysman/api.html#scheduler-functions  returns handles for each tile level   but the ** zesSchedulerSetComputeUnitDebugMode **   will work at device level as it is global function but documentation doesn't say it. Hence if user try to set for 1 tile, it will affect to other tile also which could be concern. Hence requested to update documentation to reflect the same

**Comment by saik-intel** [comment]
@jandres742   @wdamon-intel   please make sure this should be part of spec 1.7 change

**Comment by aravindksg** [comment]
based on offline discussion, current recommendation is to carry documentation regarding this in driver repo so that behavior is clearly communicated to user and not modify docs at spec level

**Comment by wdamon-intel** [comment]
@jandres742 please look

**Comment by wdamon-intel** [comment]
This is being addressed with #218, which will deprecate this API.
