### ISSUE TITLE
Deprecate ZET_ENABLE_API_TRACING_EXP

### ISSUE THREAD

**Issue by matcabral** [oneapi-src/level-zero-spec#17]
The built-in support of tracing in the spec was moved to experimental with projection to deprecate it. As previously discussed there are inherent limitations with the built-in approach, so the tracing layer was added to the loader. At the time of writtign this the tracing layer has been fully implemented for over two years, providing good grace period to transition. Therefore there is room for the deprecation of the built-in support. Today we have risk of customers trying to mix and match both levels of support.

**Comment by bashbaug** [comment]
So just to confirm: we want to deprecate the `ZET_ENABLE_API_TRACING_EXP` environment variable and signpost to the layer instead?  Something like:

> Note: This tracing environment variable is deprecated. Please use the tracing layer instead.

No other changes required?  Thanks!

**Comment by jandres742** [comment]
@bashbaug I would say:

"... use tracing layer ..." -> "use Level Zero loader tracing layer ...".

Dont know if we want to put a link: https://github.com/oneapi-src/level-zero/tree/master/source/layers/tracing
