### ISSUE TITLE
[Sysman]Report memory and GPU power

### ISSUE THREAD

**Issue by sanilkumar0** [oneapi-src/level-zero-spec#176]
To display GPU and Memory power for ARC control GUI

**Comment by sanilkumar0** [comment]
Add new sensor enum - zes_power_domain_t.ZES_POWER_DOMAIN_MEM and zes_power_domain_t.ZES_POWER_DOMAIN_GPU

**Comment by aravindksg** [comment]
missed seeing this issue earlier, we could close this as duplicate of #214
