### ISSUE TITLE
[Sysman] [Documentation] rename serial number/board number in Sysman Device properties structure 

### ISSUE THREAD

**Issue by saik-intel** [oneapi-src/level-zero-spec#179]
There is always confusion for customers with [board number](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv4N23zes_device_properties_t11boardNumberE) vs [serial number](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv4N23zes_device_properties_t12serialNumberE) mentioned in spec 

For customers who is using **S/N**  is [board number](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv4N23zes_device_properties_t11boardNumberE)

And the [serial number](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv4N23zes_device_properties_t12serialNumberE)  is **PPIN**

Can we rename/modify  [board number](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv4N23zes_device_properties_t11boardNumberE)  as board serial number 

And [serial number](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv4N23zes_device_properties_t12serialNumberE)   with other proper name to significance of it

**Comment by saik-intel** [comment]
@sanilkumar0  @vaidyan1-int   @wdamon-intel  please tag accordingly

**Comment by wdamon-intel** [comment]
Closed with #180
