### ISSUE TITLE
Description modification for zesFabricPortGetMultiPortThroughput

### ISSUE THREAD

**Issue by bellekal** [oneapi-src/level-zero-spec#195]
I see that description for zes_fabric_port_handle_t *phPort i.e phPort is inappropriate which actually describes for Enumerate call. Also, Proper documentation is needed for pThroughput saying how they will be mapped to port handle.

Some part of description for  zesFabricPortGetMultiPortThroughput is added under https://spec.oneapi.io/level-zero/latest/sysman/api.html#zesfabricportgetfabricerrorcounters which needs to be modified.

I believe a double pointer is not needed for [zes_fabric_port_throughput_t](https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv428zes_fabric_port_throughput_t) **pThroughput

**Comment by saik-intel** [comment]
@sanilkumar0  @aravindksg   can we look into this and fix asap in upcoming spec minor update
