### ISSUE TITLE
Remove time units for activeTime and timestamp fields in zes_engine_stats_t

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#197]
Proposal here is to remove “microseconds” from activeTIme and timestamp. By obfuscating the units, we can directly use hardware counters that might be counting at frequencies different than microsecs/milliseconds. It also means that when we provide numbers to VFs, customers will not be assuming that these numbers are correlated to wall time. As the description says, the only purpose for these numbers is for a percentage calculation

**Comment by aravindksg** [comment]
@saik-intel @sanilkumar0 @joshuaranjan @jandres742 @wdamon-intel

**Comment by jandres742** [comment]
this is just change on description, so we could do it on next major version.

**Comment by jandres742** [comment]
targeting v1.8. @wdamon-intel : would that be ok?

**Comment by wdamon-intel** [comment]
@matcabral what do you think?

**Comment by matcabral** [comment]
@aravindksg is your proposal limited only to zes_engine_stats_t or are you looking at doing it for all spec entries for microseconds? I think being able to draw a timeline is a desirable feature.  However, if this is only for zes_engine_stats_t i agree you would also need a way to query the source, to allow drawing a timeline with other timestamps. E.g. metrics.

**Comment by aravindksg** [comment]
> @aravindksg is your proposal limited only to zes_engine_stats_t or are you looking at doing it for all spec entries for microseconds? I think being able to draw a timeline is a desirable feature. However, if this is only for zes_engine_stats_t i agree you would also need a way to query the source, to allow drawing a timeline with other timestamps. E.g. metrics.

@matcabral this is limited to only zes_engine_stats_t. For this usage scenario, user will only be using these values for a calculation of percentage utilization. so they could plot an utilization % graph against, but time I guess would be "host"/OS gettime rather than depending on the value reported in engine_stats_t. The values in engine_stats_t are to reflect HW counters (and not necessarily to infer time for the user)

**Comment by matcabral** [comment]
Ok, I see that the proposal is to only remove it from activeTime and not the timestamp.  I agree with the idea of the change, but leaves few loopholes:

- Activetime: will rename to activecounter? 
- The formula in the description goes with time / time to get a % . will end with a unit of 1/time ?

Bw, also related to the process mapping the timestamps. The description explicitly says not do to it. But following what we did in metrics (synchronize metrics timestamps API), we should consider adding an API allow doing this in sysman.

**Comment by aravindksg** [comment]
> 



> Ok, I see that the proposal is to only remove it from activeTime and not the timestamp. I agree with the idea of the change, but leaves few loopholes:

Not only from activeTime. but remove mention of (micro)secs from both activeTime and timestamp. Both are intended to be raw counter info.

> 
> * Activetime: will rename to activecounter?
> * The formula in the description goes with time / time to get a % . will end with a unit of 1/time ?
> 

unfortunately can't rename in minor version change since it would break ABI. if we need to do that then possibly deprecate this and create new extension struct. (TBH active"time" and "time"stamp are misnomers, but it is what it is)

> Bw, also related to the process mapping the timestamps. The description explicitly says not do to it. But following what we did in metrics (synchronize metrics timestamps API), we should consider adding an API allow doing this in sysman.

as mentioned above, intention is to only provide raw counter info. so calculation would be in same "units" which may not need to be exposed to user. All user would care about is to derive  % utilization based on these two values. so for this "timestamp" value don't think we need to add new APIs to synchronize timestamps.

**Comment by matcabral** [comment]
Summary, I think the change is OK. 

My comment about the synchronization timestamp APIs is beyond the scope of this change.  There could be value for tools relating the metric collected vs the known the engine utilization at a given point in the the timeline.
