### ISSUE TITLE
Max Allocation for a Single Buffer and Extended Alloc Size 

### ISSUE THREAD

**Issue by jjfumero** [oneapi-src/level-zero-spec#2]
This question was moved from here: https://github.com/oneapi-src/level-zero/issues/88 

From the related issue, I was able to allocate more memory than the max default. 

For instance, for 8GB: 

```bash
./levelZeroAlloc 8147483648
Device   : Intel(R) UHD Graphics [0x9bc4]
Type     : GPU
Vendor ID: 8086

Allocating Shared: 8147483648 bytes - 8.14748 (GB)  ----- [OK] 
```

Just for reference, this works (e.g,, a shared memory buffer):

```cpp
ze_device_mem_alloc_desc_t memAllocDesc = {ZE_STRUCTURE_TYPE_DEVICE_MEM_ALLOC_DESC};
memAllocDesc.flags = ZE_DEVICE_MEM_ALLOC_FLAG_BIAS_CACHED;
memAllocDesc.ordinal = 0;

ze_host_mem_alloc_desc_t hostDesc = {ZE_STRUCTURE_TYPE_HOST_MEM_ALLOC_DESC};

ze_relaxed_allocation_limits_exp_desc_t exceedCapacity = {
        ZE_STRUCTURE_TYPE_RELAXED_ALLOCATION_LIMITS_EXP_DESC,
        nullptr, 
        ZE_RELAXED_ALLOCATION_LIMITS_EXP_FLAG_MAX_SIZE
    };

void *sharedBuffer = nullptr;

hostDesc.pNext = &exceedCapacity;
memAllocDesc.pNext = &exceedCapacity;

result = zeMemAllocShared(context, &memAllocDesc, &hostDesc, allocSize, 128, device, &sharedBuffer);
```

A follow-up question is from the comment in the SPEC:

> Allocation size may exceed [ze_device_properties_t.maxMemAllocSize](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=device_memory_properties#structze__device__properties__t_1a10e099e2ccbac99a4f2e8c7c13f20b79).

https://github.com/oneapi-src/level-zero/blob/master/include/ze_api.h#L6312 

Does this mean that the requested extended size is not guaranteed?

**Comment by jandres742** [comment]
hi @jjfumero 

so, when you use ZE_STRUCTURE_TYPE_RELAXED_ALLOCATION_LIMITS_EXP, you can allocate more than maxMemAllocSize, as you found out. The reason the spec says "may exceed" is because there could be situations where the driver cannot allocate more than that because of HW or runtime restrictions. In that sense, "may" is used to indicate that with this extension you can allocate more memory than maxMemAllocSize, but allocation call could return OUT_OF_MEMORY, or the extension might not be implemented at all and still be L0 compliant.

**Comment by jjfumero** [comment]
I have a follow-up question:
 - Is the extended allocation mode expected to work also for Intel discrete GPUs? or this only applies to shared memory systems?

From the spec I see this can also be applied [zeMemAllocDevice](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1ad47b7ece6b6c412dbb96fbe0afd89147)

https://spec.oneapi.io/level-zero/latest/core/api.html#ze-relaxed-allocation-limits-exp-desc-t

**Comment by jandres742** [comment]
@jjfumero it applies to all, as mentioned there:

This structure may be passed to [zeMemAllocShared](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1aa487327d7e6a961daa87dd6ec04f570b) or [zeMemAllocDevice](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1ad47b7ece6b6c412dbb96fbe0afd89147), via pNext member of [ze_device_mem_alloc_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#structze__device__mem__alloc__desc__t).

This structure may also be passed to [zeMemAllocHost](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a920bf06c295d03b78ccf4e2f20dfa336), via pNext member of [ze_host_mem_alloc_desc_t](https://spec.oneapi.io/level-zero/latest/core/api.html#structze__host__mem__alloc__desc__t).

**Comment by jjfumero** [comment]
That's great! Looking forward to testing this on Intel's discrete GPUs.
