### ISSUE TITLE
Add mechanism to gather memory utilization info for all VFs

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#209]
Add extension capability to current API `zesMemoryGetState` to gather memory utilization info for all VFs from PF (similar to `zesGetEngineActivityExt`)

**Comment by aravindksg** [comment]
@sanilkumar0 @jandres742 @joshuaranjan @saik-intel @wdamon-intel

**Comment by jandres742** [comment]
@sanilkumar0 : could you take a look?

**Comment by sanilkumar0** [comment]
Similar to Engine activity reported perf VF, Memory usage reporting per VF is required. Create  zesMemoryGetStateExt with 'free' and 'size' fields

**Comment by saik-intel** [comment]
@aravindksg  is PR raised for this ?

**Comment by aravindksg** [comment]
Closing as we are moving to new set of VF interfaces with #248
