### ISSUE TITLE
Add mechanism to expose IFWI version number

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#213]
IFWI versions have specific layout. Request here is to add capability to expose that

**Comment by jandres742** [comment]
@aravindksg : what do you mean about layout?

**Comment by sanilkumar0** [comment]
typedef struct global_ifwi_version{
    UINT16 Product_version;
    UINT16 Release_version;
    UINT16 Build_version;
    UINT16 Hotfix_version;
    UINT16 Engineering_version;
    }ifwi_version_t;

**Comment by aravindksg** [comment]
Closing issue since we can't add vendor specific struct
