### ISSUE TITLE
Add new sysman engine group enumerator for MEDIA_CODEC_SINGLE

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#217]
This allows for engine group stats to be reported if independent counters for encode/decode functions are not available

**Comment by aravindksg** [comment]
@sanilkumar0 @jandres742 @wdamon-intel @saik-intel @joshuaranjan

**Comment by jandres742** [comment]
@sanilkumar0 : please check.

**Comment by aravindksg** [comment]
this is being addressed as part of https://github.com/oneapi-src/level-zero-spec/pull/74

**Comment by wdamon-intel** [comment]
Resolved with #74
