### ISSUE TITLE
Deprecate zesSchedulerSetComputeUnitDebugMode API

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#218]
- Given this is debug related, it does not really belong to Scheduler API set
- there is no use case currently for per-device switches for debugger
- For debugger enablement, global envvar is currently used ZET_ENABLE_PROGRAM_DEBUGGING and for device level masking ZE_AFFINITY_MASK is used already

**Comment by jandres742** [comment]
@aravindksg : is this implemented in the L0 GPU driver?

**Comment by bmyates** [comment]
This is implemented in the intel gpu driver for linux. It is not implemented for windows. 

The current implementation is toggling KMD eudebug feature enable by sysfs write. There are no users of this API.  Instead, we instruct users to directly write the sysfs file node. 

ZET_ENABLE_PROGRAM_DEBUGGING is used as UMD enable, and does not directly enable debugging in KMD.
