### ISSUE TITLE
New API to wait for 64b memory value

### ISSUE THREAD

**Issue by BartoszDunajski** [oneapi-src/level-zero-spec#246]
Existing zexCommandListAppendWaitOnMemory supports only 32b values. It limits many use cases. For example counter overflow.
Additionally, "write" API (zexCommandListAppendWriteToMemory) uses 64b data type.

To dont break existing code, we should keep zexCommandListAppendWaitOnMemory and add new zexCommandListAppendWaitOnMemory**64**  version. 

64b waits may be not supported by all GPUs. API will return ZE_RESULT_ERROR_UNSUPPORTED_FEATURE then.

**Comment by MichalMrozek** [comment]
We need some query mechanism here that would report properly the wait counter size value to the application.

**Comment by jandres742** [comment]
thanks @BartoszDunajski . zexCommandListAppendWaitOnMemory https://github.com/intel/compute-runtime/blob/master/level_zero/doc/experimental_extensions/WAIT_AND_WRITE_ON_MEMORY.md  is not yet in the spec, but we are thinking on adding it, so we could add it with the 64b support you mentioned. Thanks.

**Comment by BartoszDunajski** [comment]
API merged: https://github.com/intel/compute-runtime/commit/0a99d389cebaacf1c797592b35b10d9bc49025e1
