### ISSUE TITLE
Add interface to retrieve kernel binary

### ISSUE THREAD

**Issue by echeresh** [oneapi-src/level-zero-spec#247]
With OpenCL we can use `clGetKernelInfo()` to access the kernel binary:

```
clGetKernelInfo(kernel, CL_KERNEL_BINARY_PROGRAM_INTEL);
// Dump binary to a file ...
// Use iga64 to disassemble:
// iga64 -d ...
```

Level Zero is missing a similar API. There is `zeModuleGetNativeBinary()` but it returns a \*module\* binary which can't be used with `iga64`.

**Comment by rwmcguir** [comment]
Implemented by Commit 7ef52fa
