### ISSUE TITLE
Add Sysman event for notifying when graphics driver stops working

### ISSUE THREAD

**Issue by aravindksg** [oneapi-src/level-zero-spec#253]
Add new event enumeration for a "survivability event" to notify users when kernel mode driver stops working

**Comment by wdamon-intel** [comment]
@aravindksg is this the same as #251 ?

**Comment by aravindksg** [comment]
> @aravindksg is this the same as #251 ?

yes, apologies, I didn't notice the earlier one. I'll close #251 as in PR we are referencing #253
