### ISSUE TITLE
Experimental extension to append command lists to an immediate command list

### ISSUE THREAD

**Issue by wdamon-intel** [oneapi-src/level-zero-spec#258]
# Summary
Introduce an experimental extension to append a batch of command lists to an immediate command list.

# Details

## Motivation
In order to efficiently support certain use-cases, such as compute graphs, it is desirable to have the ability to append the dispatch of recorded command list(s) to an immediate command list.
 
#### zeCommandListImmediateAppendCommandListsExp
Appends command lists to dispatch from an immediate command list.

```cpp
ze_result_t zeCommandListImmediateAppendCommandListsExp(
    ze_command_list_handle_t hCommandListImmediate,
    uint32_t numCommandLists,
    ze_command_list_handle_t *phCommandLists,
    ze_event_handle_t hSignalEvent,
    uint32_t numWaitEvents,
    ze_event_handle_t *phWaitEvents
);
```

| Parameter  | Description |
| :---------- | :---------------------------------------- |
| **hCommandListImmediate** | \[ ${\textsf{\color{orange}in}}$ \] handle of the immediate command list |
| **numCommandLists** | \[ ${\textsf{\color{orange}in}}$ \] number of command lists |
| **phCommandLists** | \[ ${\textsf{\color{orange}in}}$ \]\[ ${\textsf{\color{lightgreen}range\(0, numCommandLists\)}}$ \] handle\(s\) of command list\(s\) |
| **hSignalEvent** | \[ ${\textsf{\color{orange}in}}$ \]\[ ${\textsf{\color{lightblue}optional}}$ \] handle of the event to signal on completion |
| **numWaitEvents** | \[ ${\textsf{\color{orange}in}}$ \] number of events to wait on before executing appended command lists; must be 0 if `nullptr == phWaitEvents` |
| **phWaitEvents** | \[ ${\textsf{\color{orange}in}}$ \]\[ ${\textsf{\color{lightblue}optional}}$ \]\[ ${\textsf{\color{lightgreen}range\(0, numWaitEvents\)}}$ \] handle of the events to wait on before executing appended command lists |

##### Notes
- this function causes the execution of the batch of command lists in `phCommandLists` in a similar way to `zeCommandQueueExecuteCommandLists`
- the `hCommandListImmediate` command list parameter must be created with `zeCommandListCreateImmediate`
- the command list or lists in `phCommandLists` must be "regular" command lists (i.e. *not* immediate command lists)
- if not null, `hSignalEvent` is signaled after the completion of all appended command lists
- if not null, all wait events in `phWaitEvents` must be satisfied prior to the start of any appended command list(s)

**Comment by MichalMrozek** [comment]
Looks good to me.
