### ISSUE TITLE
Experimental extension to mutate commands in a command list

### ISSUE THREAD

**Issue by wdamon-intel** [oneapi-src/level-zero-spec#260]
# Summary
Introduce an experimental extension to mutate commands in a command list.

# Details

## Motivation
In order to efficiently support certain use-cases, such as compute graphs with dynamic parameters, it is desirable to have the ability to mutate commands within a recorded command list.
 
## Interoperability with Other Extensions
- This extension is complimentary to and may be used in conjunction with **ZE\_experimental\_command\_list\_clone**

### New Enumerations

**ze\_mutable\_command\_id\_exp\_flags\_t**
- mutable command identifier flags

**ze\_mutable\_command\_list\_exp\_flags\_t**
- mutable command list flags

### New Structures

**ze\_mutable\_command\_id\_exp\_desc\_t**
- Mutable command identifier descriptor

**ze\_mutable\_command\_list\_exp\_desc\_t**
- Mutable command list descriptor

**ze\_mutable\_commands\_exp\_desc\_t**
- Mutable commands descriptor

**ze\_mutable\_kernel\_argument\_exp\_desc\_t**
- Mutable kernel argument descriptor

**ze\_mutable\_group\_count\_exp\_desc\_t**
- Mutable kernel group count descriptor

**ze\_mutable\_group\_size\_exp\_desc\_t**
- Mutable kernel group size descriptor

**ze\_mutable\_global\_offset\_exp\_desc\_t**
- Mutable kernel global offset descriptor

#### zeCommandListGetNextCommandIdExp
This function returns a unique command identifier for the next command to be appended to a command list.

```cpp
ze_result_t zeCommandListGetNextCommandIdExp(
    ze_command_list_handle_t hCommandList,
    const ze_mutable_command_id_exp_desc_t* desc,
    uint64_t* pCommandId
);
```

| Parameter  | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of the command list |
| desc | \[ ${\textsf{\color{orange}in}}$ \] pointer to mutable command identifier descriptor |
| pCommandId | \[ ${\textsf{\color{yellow}out}}$ \] pointer to mutable command identifier to be written |

##### Notes
- this function may only be called for a mutable command list
- this function may not be called on a closed command list

---

#### zeCommandListUpdateMutableCommandsExp
This function updates mutable commands in a mutable command list.

```cpp
ze_result_t zeCommandListUpdateMutableCommandsExp(
    ze_command_list_handle_t hCommandList,
    const ze_mutable_commands_exp_desc_t* desc
);
```

| Parameter  | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of the command list |
| desc | \[ ${\textsf{\color{orange}in}}$ \] pointer to mutable commands descriptor; multiple descriptors may be chained via `pNext` member |

##### Notes
- this function may only be called for a mutable command list
- the application must synchronize a mutable command list before calling this function
- the application must close a mutable command list after completing all updates

---

#### zeCommandListUpdateMutableCommandSignalEventExp
This function updates the signal event for a mutable command in a mutable command list.

```cpp
ze_result_t zeCommandListUpdateMutableCommandSignalEventExp(
    ze_command_list_handle_t hCommandList,
    uint64_t commandId,
    ze_event_handle_t hSignalEvent
);
```

| Parameter  | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of the command list |
| commandId | \[ ${\textsf{\color{orange}in}}$ \] command identifier |
| hSignalEvent | \[ ${\textsf{\color{orange}in}}$ \]\[ ${\textsf{\color{lightblue}optional}}$ ] handle of the event to signal on completion |

##### Notes
- this function may only be called for a mutable command list
- the type, scope and flags of the signal event must match those of the source command
- passing a null pointer as the signal event will update the command to not issue a signal
- the application must synchronize a mutable command list before calling this function
- the application must close a mutable command list after completing all updates

---

#### zeCommandListUpdateMutableCommandWaitEventsExp
This function updates the wait events for a mutable command in a mutable command list.

```cpp
ze_result_t zeCommandListUpdateMutableCommandWaitEventsExp(
    ze_command_list_handle_t hCommandList,
    uint64_t commandId,
    ze_event_handle_t* phWaitEvents
);
```

| Parameter  | Description |
| :---------- | :---------------------------------------- |
|hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of the command list |
|commandId | \[ ${\textsf{\color{orange}in}}$ \] command identifier |
|phWaitEvents | \[ ${\textsf{\color{orange}in}}$ \]\[ ${\textsf{\color{lightblue}optional}}$ \]\[ ${\textsf{\color{lightgreen}range\(0, numWaitEvents\)}}$ \] handle of the events to wait on before launching |

##### Notes
- this function may only be called for a mutable command list
- the number of wait events must match that of the source command
- the type, scope and flags of the wait events must match those of the source command
- passing `nullptr` as the wait events will update the command to not wait on any events prior to dispatch
- passing `nullptr` as an event on event wait list will remove event dependency from this wait list slot
- the application must synchronize a mutable command list before calling this function
- the application must close a mutable command list after completing all updates

---

#### Creating a Mutable Command List

```cpp
// Create a mutable command list
ze_mutable_command_list_exp_desc_t mutCmdListDesc = {
    ZE_STRUCTURE_TYPE_MUTABLE_COMMAND_LIST_EXP_DESC,
    nullptr,
    0 // flags
};

ze_command_list_desc_t commandListDesc = {
    ZE_STRUCTURE_TYPE_COMMAND_LIST_DESC,
    &mutCmdListDesc,
    0,
    0 // flags
};

ze_command_list_handle_t hCommandList = nullptr;
zeCommandListCreate(hContext, hDevice, &commandListDesc, &hCommandList);

// [ ...create fence, signal event and wait event objects... ]
// This example assumes hFence, hSignalEvent and hWaitEvent have been created.

// Create kernel from module
ze_kernel_desc_t kernelDesc = {
    ZE_STRUCTURE_TYPE_KERNEL_DESC,
    0,
    "example"
};
ze_kernel_handle_t hKernel = nullptr;
ze_result_t result = zeKernelCreate(hModule, &kernelDesc, &hKernel);

// Set the kernel arguments
ze_group_count_t groupSize = {};
zeKernelSuggestGroupSize(hKernel, 1024, 1024, 1, &groupSize.groupCountX, &groupSize.groupCountY, &groupSize.groupCountZ);

int defaultValue = 0;
zeKernelSetArgumentValue(hKernel, 0, sizeof(int), &defaultValue);

// Get next command identifier
ze_mutable_command_id_exp_desc_t cmdIdDesc = {
    ZE_STRUCTURE_TYPE_MUTABLE_COMMAND_ID_EXP_DESC       // stype
    nullptr,                                            // pNext
    0                                                   // flags
};

uint64_t commandId = 0;
zeCommandListGetNextCommandIdExp(hCommandList, &cmdIdDesc, &commandId);

// Encode command into command list
zeCommandListAppendLaunchKernel(hCommandList, hKernel, &groupSize, hSignalEvent, 1, &hWaitEvent);

// Close the command list
zeCommandListClose(hCommandList);

// ...

// Execute the command list
zeCommandQueueExecuteCommandLists(hCommandQueue, 1, &hCommandList, hFence);

// ...
```

#### Mutating Commands and Events

```cpp
// Modify group count
ze_group_count_t groupCount = {
    256,                                                    // groupCountX
    256,                                                    // groupCountY
    1                                                       // groupCountZ
};

ze_mutable_group_count_exp_desc_t groupCountDesc = {
    ZE_STRUCTURE_TYPE_MUTABLE_GROUP_COUNT_EXP_DESC,         // stype
    nullptr,                                                // pNext
    commandId,                                              // commandId
    &groupCount                                             // pGroupCount
};

// Modify Kernel Argument
int argValue = 1;

ze_mutable_kernel_argument_exp_desc_t krnlArgDesc = {
    ZE_STRUCTURE_TYPE_MUTABLE_KERNEL_ARGUMENT_EXP_DESC,     // stype
    &groupCountDesc,                                        // pNext
    commandId,                                              // commandId
    0,                                                      // argIndex
    sizeof(int),                                            // argSize
    &argValue                                               // pArgValue
};

// Prepare to update all mutable commands
ze_mutable_commands_exp_desc_t desc = {
    ZE_STRUCTURE_TYPE_MUTABLE_COMMANDS_EXP_DESC,            // stype
    &krnlArgDesc,                                           // pNext
    0                                                       // flags
};

// Synchronize the mutable command list
zeFenceHostSynchronize(hFence, UINT64_MAX);

// Update all mutable commands
zeCommandListUpdateMutableCommandsExp(hCommandList, &desc);

// Update signal event for the launch kernel command
zeCommandListUpdateMutableCommandSignalEventExp(hCommandList, commandId, hNewLaunchKernelSignalEvent);

// Update the wait event list for the launch kernel command
// Note, this example uses only a single wait event for the kernel
zeCommandListUpdateMutableCommandWaitEventsExp(hCommandList, commandId, &hNewLaunchKernelWaitEvent);

// Close the command list
zeCommandListClose(hCommandList);

// ...
```

**NOTE**: the command list must be explicitly closed after updating mutable commands and events

**Comment by MichalMrozek** [comment]
yes

**Comment by wdamon-intel** [comment]
> if the command list is in execution, shall we wait for it to finish before zeCommandListUpdateMutableCommandsExp?

This is a great question. As Michal noted, the answer is 'yes', and I have updated the Notes sections for the Update APIs to explicitly call this out.

**Comment by zzdanowicz** [comment]
@guoyejun 
Instance of command list cannot be modified when referenced by the device, since "implementation is allowed to modify the contents of the command list for submission" - and it includes immutable command lists, so it naturally extends into mutable command lists:
https://spec.oneapi.io/level-zero/latest/core/api.html#zecommandqueueexecutecommandlists

**Comment by wdamon-intel** [comment]
> In the example `zeCommandListAppendLaunchKernel(hCommandList, hKernel, &groupSize, nullptr, 0, nullptr);` signal event is null and waitlist is 0. So there is lack of event types, scopes, wait events count provided at initial encoding and mutation of signal and waitlist is invalid?

The example should include a signal and wait event list on the kernel command.

**Comment by wdamon-intel** [comment]
> > In the example `zeCommandListAppendLaunchKernel(hCommandList, hKernel, &groupSize, nullptr, 0, nullptr);` signal event is null and waitlist is 0. So there is lack of event types, scopes, wait events count provided at initial encoding and mutation of signal and waitlist is invalid?
> 
> The example should include a signal and wait event list on the kernel command.

Example updated.

**Comment by guoyejun** [comment]
looks that ze_mutable_kernel_argument_exp_desc_t  can support only one arg to mutate?

**Comment by guoyejun** [comment]
question: what will be the user scenery when a host side sync is required?

**Comment by zzdanowicz** [comment]
> looks that ze_mutable_kernel_argument_exp_desc_t can support only one arg to mutate?

You can link multiple kernel argument updates, example:
```
int scalarArgValue = 1;

ze_mutable_kernel_argument_exp_desc_t krnlArg0Desc = {
    ZE_STRUCTURE_TYPE_MUTABLE_KERNEL_ARGUMENT_EXP_DESC,
    nullptr,
    commandId,
    0,  // argIndex
    sizeof(int),
    &scalarArgValue 
};

void *allocatedUsmMemory;

ze_mutable_kernel_argument_exp_desc_t krnlArg1Desc = {
    ZE_STRUCTURE_TYPE_MUTABLE_KERNEL_ARGUMENT_EXP_DESC,
    &krnlArg0Desc, // link two kernel argument updates
    commandId,
    1,  // next argIndex
    sizeof(void *),
    &allocatedUsmMemory
};

ze_mutable_commands_exp_desc_t updateDesc = {
    ZE_STRUCTURE_TYPE_MUTABLE_COMMANDS_EXP_DESC,
    &krnlArg1Desc,
    0
};
```

Can you provide feedback on it?

**Comment by guoyejun** [comment]
> Can you provide feedback on it?

looks good, thanks
