### ISSUE TITLE
Introspection APIs to support device-side profiling started at the middle of an application execution 

### ISSUE THREAD

**Issue by jfedorov** [oneapi-src/level-zero-spec#267]
# Summary

Introduce core APIs to request basic info on command list, command queue and events from their handles. 

#  Details 

## Motivation

In order to efficiently trace device side execution of AI applications using PyTorch, PTI profiling library needs to be able to start profiling at arbitrary point of an application. Prior to this point the library won't be tracing Level Zero call - e.g. those creating Events, Command lists, Queues. PTI would need to reconstruct their properties when at the profiling Start and intercepting some zeCommandListAppendLaunchKernel (or similar operations re- MemoryCopy etc).

#### zeCommandQueueGetOrdinal

```cpp
ze_result_t zeCommandQueueGetOrdinal
    ze_command_queue_handle_t hCommandQueue,
    uint32_t* pOrdinal
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandQueue| \[ ${\textsf{\color{orange}in}}$ \] handle of command queue |
| pOrdinal | \[ ${\textsf{\color{yellow}out}}$ \] command queue group ordinal |

---

#### zeCommandQueueGetIndex

```cpp
ze_result_t zeCommandQueueGetIndex(
    ze_command_queue_handle_t hCommandQueue,
    uint32_t* pIndex
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandQueue| \[ ${\textsf{\color{orange}in}}$ \] handle of command queue |
| pIndex | \[ ${\textsf{\color{yellow}out}}$ \] command queue index within the group |

---

#### zeCommandListGetDeviceHandle

```cpp
ze_result_t zeCommandListGetDeviceHandle(
    ze_command_list_handle_t hCommandList,
    ze_device_handle_t* phDevice
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of command list |
| phDevice | \[ ${\textsf{\color{yellow}out}}$ \] handle of device on which command list was created |

---

#### zeCommandListGetContextHandle

```cpp
ze_result_t zeCommandListGetContextHandle(
    ze_command_list_handle_t hCommandList,
    ze_context_handle_t* phContext
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of command list |
| phContext | \[ ${\textsf{\color{yellow}out}}$ \] handle of context on which command list was created |

---

#### zeCommandListGetOrdinal

```cpp
ze_result_t zeCommandListGetOrdinal(
    ze_command_list_handle_t hCommandList,
    uint32_t* pOrdinal
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of command list |
| pOrdinal | \[ ${\textsf{\color{yellow}out}}$ \] command queue group ordinal to which command list is submitted |

---

#### zeCommandListImmediateGetIndex

```cpp
ze_result_t zeCommandListImmediateGetIndex(
    ze_command_list_handle_t hCommandListImmediate,
    uint32_t* pIndex
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandListImmediate | \[ ${\textsf{\color{orange}in}}$ \] handle of command list |
| pIndex | \[ ${\textsf{\color{yellow}out}}$ \] command queue index within the group to which immediate command list is submitted |

---

#### zeCommandListIsImmediate

```cpp
ze_result_t zeCommandListIsImmediate(
    ze_command_list_handle_t hCommandList,
    ze_bool_t* pIsImmediate
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hCommandList | \[ ${\textsf{\color{orange}in}}$ \] handle of command list |
| pIsImmediate | \[ ${\textsf{\color{yellow}out}}$ \] Boolean indicating whether command list is immediate |

---

#### zeEventGetEventPool

```cpp
ze_result_t zeEventGetEventPool(
    ze_event_handle_t hEvent,
    ze_event_pool_handle_t* phEventPool
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hEvent | \[ ${\textsf{\color{orange}in}}$ \] handle of event |
| phEventPool | \[ ${\textsf{\color{yellow}out}}$ \] handle of event's event pool |

---

#### zeEventPoolGetContextHandle

```cpp
ze_result_t zeEventPoolGetContextHandle(
    ze_event_pool_handle_t hEventPool,
    ze_context_handle_t* phContext
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hEventPool | \[ ${\textsf{\color{orange}in}}$ \] handle of event pool |
| phContext | \[ ${\textsf{\color{yellow}out}}$ \] handle of context on which event pool was created |

---

#### zeEventPoolGetFlags

```cpp
ze_result_t zeEventPoolGetFlags(
    ze_event_pool_handle_t hEventPool,
    ze_event_pool_flags_t* pFlags
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hEventPool | \[ ${\textsf{\color{orange}in}}$ \] handle of event pool |
| pFlags | \[ ${\textsf{\color{yellow}out}}$ \] creation flags. May be 0 or a valid combination of ze_event_pool_flag_t flags. |

---

#### zeEventGetSignalScope

```cpp
ze_result_t zeEventGetSignalScope(
    ze_event_handle_t hEvent,
    ze_event_scope_flags_t* pSignalScope
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hEvent | \[ ${\textsf{\color{orange}in}}$ \] handle of event |
| pSignalScope | \[ ${\textsf{\color{yellow}out}}$ \] signal event scope. This is the scope of relevant cache hierarchies that are flushed on a signal action before the event is triggered. May be 0 or a valid combination of ze_event_scope_flag_t. |

---

#### zeEventGetWaitScope

```cpp
ze_result_t zeEventGetWaitScope(
    ze_event_handle_t hEvent,
    ze_event_scope_flags_t* pWaitScope
);
```

| Parameter | Description |
| :---------- | :---------------------------------------- |
| hEvent | \[ ${\textsf{\color{orange}in}}$ \] handle of event |
| pWaitScope | \[ ${\textsf{\color{yellow}out}}$ \] wait event scope. This is the scope of relevant cache hierarchies invalidated on a wait action after the event is complete. May be 0 or a valid combination of ze_event_scope_flag_t. |

**Comment by MichalMrozek** [comment]
for those descriptor returning calls, do you really need to get full blown descriptor or just some flag fields?
Majority of the descriptor is not needed after the call, it would add overhead to store it, especially for cases where there are multiple levels of pNext nesting and driver would need to dynamically allocate each level to create a copy.

i.e. for command queue ze_command_queue_flags_t  ?

**Comment by wdamon-intel** [comment]
> for those descriptor returning calls, do you really need to get full blown descriptor or just some flag fields? Majority of the descriptor is not needed after the call, it would add overhead to store it, especially for cases where there are multiple levels of pNext nesting and driver would need to dynamically allocate each level to create a copy.
> 
> i.e. for command queue ze_command_queue_flags_t ?

...additionally, who would own the dynamically allocated `pNext` memory -- who would be responsible for freeing it?

It will probably be better to not reconstruct the descriptor, but query for the information needed.

**Comment by jfedorov** [comment]
> > for those descriptor returning calls, do you really need to get full blown descriptor or just some flag fields? Majority of the descriptor is not needed after the call, it would add overhead to store it, especially for cases where there are multiple levels of pNext nesting and driver would need to dynamically allocate each level to create a copy.
> > i.e. for command queue ze_command_queue_flags_t ?
> 
> ...additionally, who would own the dynamically allocated `pNext` memory -- who would be responsible for freeing it?
> 
> It will probably be better to not reconstruct the descriptor, but query for the information needed.

Yes. I can suggest APIs to query information needed. 
But what worries me - that if e.g. the event description will be extended - then I would need go over this again. 

For pNext - I think - should the caller just zero this field (?) . As this is anyway implementation detail - and caller doesn't know how to interpret the information that will be there... 
Can you please advise?
