### ISSUE TITLE
zeCommandQueueExecuteCommandLists and other API's doesn't allow to return ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY / ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY 

### ISSUE THREAD

**Issue by MichalMrozek** [oneapi-src/level-zero-spec#29]
zeCommandQueueExecuteCommandLists and other API's doesn't allow to return ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY / ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY. There are use cases where such error are appropriate, so those calls should allow to return those errors.

**Comment by jandres742** [comment]
thanks @MichalMrozek .  I think this is very needed. We could put it in 1.5

@bashbaug : Let me know what you think. I can prepare PR.

**Comment by jandres742** [comment]
also @bashbaug : do we want this error code on others (or maybe all) calls?

**Comment by bashbaug** [comment]
Yeah, I think we'll want to have `ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY` as a possible result value from all calls, just like `CL_OUT_OF_HOST_MEMORY`.  We should be able to do this in the scripts rather than modifying every API.

If we're OK having `ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY` on every API we could add it similarly.  If we want to be more selective it'll be a little more work.  For reference, OpenCL allows `CL_OUT_OF_RESOURCES` on many API calls but not all, though I'm not sure the selectivity buys much.

**Comment by jandres742** [comment]
thanks @bashbaug . Marking as v1.5.

**Comment by jandres742** [comment]
@bashbaug : Please see https://github.com/oneapi-src/level-zero-spec/pull/30

**Comment by jandres742** [comment]
@bashbaug : I'm thinking we should add also ERROR_UNKONWN and ERROR_UNSUPPORTED as default errors for all APIs, to allow L0 driver to return an error that doesnt fit the description of any other, and when a given API has not yet been implemented.

**Comment by bashbaug** [comment]
> I'm thinking we should add also ERROR_UNKNOWN and ERROR_UNSUPPORTED as default errors for all APIs, to allow L0 driver to return an error that doesnt fit the description of any other, and when a given API has not yet been implemented.

I don't think it makes sense to add these errors unconditionally:

* `ERROR_UNKNOWN` shouldn't ever happen in theory.  If an error condition is missing in the specification, we should add it.
* `ERROR_UNSUPPORTED` may make sense in some cases, when a function is optional, but it doesn't make sense in a general case.

**Comment by jandres742** [comment]
thanks @bashbaug . What error L0 drivers should return when an official interface has been defined in the spec but not yet implemented in the driver because of any reason?

**Comment by bashbaug** [comment]
> What error L0 drivers should return when an official interface has been defined in the spec but not yet implemented in the driver because of any reason?

Would this ever happen for a "conformant" driver?

If not, a non-conformant driver could do whatever it wants, because it is non-conformant.
