### ISSUE TITLE
Enable querying of position index in event pool from an event handle

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/level-zero-spec#3]
L0 event interface involves position index inside event pool. However, given an event handle, there is no way to tell what the index was, which complicates the situation when people freed the event and want to reuse the slot. It would be nicer to have an interface querying the index from the handler, or return it when free the event like ```zeEventDestroyAndReturnIndex(ze_event_handle, uint32_t &index)```

**Comment by jandres742** [comment]
hi @CaoZhongZ . Thanks for the comment. 
When an application is creating an event, it needs to pass an index to the pool. So it is the expectation that the application can have a mapping of L0 event and index, to know which index is available for reuse.

More, if an application wants to reuse an event for a new workload, it doesnt need to actually destroy it and create it again, All that it needs is to call `zeEventHostReset` to reset it to state when it was first created.

**Comment by CaoZhongZ** [comment]
Oh I see, thanks!
