### ISSUE TITLE
confusing diagram tools_sysman_object_hierarchy

### ISSUE THREAD

**Issue by bashbaug** [oneapi-src/level-zero-spec#33]
The diagram in the sysman initialization section "tools_sysman_object_hierarchy" is confusing:

https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#initialization

* There is a typo in the function name and it should have a `zet` prefix instead of `xet`.
* The function doesn't seem to exist.  Should it simply be a cast instead?

**Comment by jandres742** [comment]
@bashbaug : right. I think that this is a leftover from before. I think we could just remove it in favor of the new changes coming in https://github.com/oneapi-src/level-zero-spec/issues/7, https://github.com/oneapi-src/level-zero-spec/pull/34
