### ISSUE TITLE
v1.4.0 Issues

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero-spec#4]
Hello,
Here are the issues I encountered/noticed while integrating the latest specification in THAPI:

- New structures with missing entries in `ze_structure_type_t` enumerations:
   * `ze_fabric_vertex_exp_properties_t` (should be named `ZE_STRUCTURE_TYPE_FABRIC_VERTEX_EXP_PROPERTIES`)
   * `ze_fabric_edge_exp_properties_t` (should be named `ZE_STRUCTURE_TYPE_FABRIC_EDGE_EXP_PROPERTIES`)
- New structures with missing entries in `zes_structure_type_t` enumeration:
   * `zes_device_ecc_desc_t` (should be named `ZES_STRUCTURE_TYPE_DEVICE_ECC_DESC`)
   * `zes_device_ecc_properties_t` (should be named `ZES_STRUCTURE_TYPE_DEVICE_ECC_PROPERTIES`)
   * `zes_power_limit_ext_desc_t` (should be named `ZES_STRUCTURE_TYPE_POWER_LIMIT_EXT_DESC`)
   * `zes_power_ext_properties_t` (should be named `ZES_STRUCTURE_TYPE_POWER_EXT_PROPERTIES`)
- `zeDeviceGetFabricVertexExp` first argument should be named `hDevice` not `hVertex`
- `zeDeviceGetFabricVertexExp` second argument should be named `phVertex` not `pVertex`
- `zeFabricVertexGetDeviceExp` second argument should be named `phDevice` not `pDevice`

Best
Brice

**Comment by bmyates** [comment]
Hi @Kerilk, thanks for the report! We are looking into this and will update soon.

**Comment by bmyates** [comment]
Should be fixed now. https://github.com/oneapi-src/level-zero/releases/tag/v1.8.1

**Comment by Kerilk** [comment]
Looking good, will confirm everything fixed early next week when I get the chance.

**Comment by Kerilk** [comment]
The `stype` field of `struct _zes_power_limit_ext_desc_t` should be of type `zes_structure_type_t` and not `ze_structure_type_t`.

**Comment by bmyates** [comment]
@Kerilk Fixed here https://github.com/oneapi-src/level-zero/releases/tag/v1.8.5

**Comment by Kerilk** [comment]
Thanks for the update.
