### ISSUE TITLE
zeMemAlloc* maximun size should be less *or equal* than maxMemAllocSize

### ISSUE THREAD

**Issue by TApplencourt** [oneapi-src/level-zero-spec#42]
Hi,

zeMemAllocShared [stipulate](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=maxmemallocsize#zememallocshared)
```
size – [in] size in bytes to allocate; must be less than [ze_device_properties_t.maxMemAllocSize]
```
I think it should be said `less or equal`.

Indeed a common idiom is to query for `ze_device_properties_t.maxMemAllocSize` and then Allocate this amount of data.
Remembering to subtract  1 to `maxMemAllocSize`  is error-prone.

In openCL [CL_​DEVICE_​MAX_​MEM_​ALLOC_​SIZE](https://registry.khronos.org/OpenCL/specs/2.2/html/OpenCL_API.html#CL_DEVICE_MAX_MEM_ALLOC_SIZE) is `Max size of memory object allocation in bytes.` and not `max minus one size of memory object allocation in bytes.`

**Comment by jandres742** [comment]
thanks @TApplencourt . I think this is valid.
@bashbaug : what do you think?

**Comment by TApplencourt** [comment]
Thanks a lot!
