### ISSUE TITLE
Bogus zesMemoryGetBandwidth() documentation

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero-spec#45]
See zesMemoryGetBandwidth() documentation: https://spec.oneapi.io/level-zero/latest/sysman/api.html#zesmemorygetbandwidth

It claims following:
> Parameters
> * hMemory: [in] Handle for the component.
>  * pBandwidth: [in,out] Will contain the current health, free memory, total memory size.

Although `zes_mem_bandwidth_t` struct includes *none* of listed items: https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv419zes_mem_bandwidth_t

**Comment by zackwaters** [comment]
@eero-t @AstroVPK Thanks for alerting me to this. I've transferred this issue to Level Zero repo so that it will get the proper attention.

**Comment by jandres742** [comment]
@zackwaters : what would you like to do here? either we need to change the description to reflect exactly what we return, or update the struct. The former is easier as it doesnt break compatibility.

**Comment by zackwaters** [comment]
@jandres742 I think the former which is to describe what's the bandwidth struct is returning.

**Comment by jandres742** [comment]
@zackwaters : Please see here https://github.com/oneapi-src/level-zero-spec/pull/46
