### ISSUE TITLE
Define new interface for parsing the raw timestamps into time units.

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/level-zero-spec#55]
L0 currently only has interfaces that return timestamps on its raw form. While this is useful for some tools, it would be of benefit if L0 also returns the timestamps mapped to the host, similar to clGetDeviceAndHostTimer. 
Idea here is to define a new interface for this.

**Comment by aravindksg** [comment]
@jandres742  not exactly similar to clGetDeviceAndHostTimer (for which we have `zeDeviceGetGlobalTimestamps`), but something similar to https://man.opencl.org/clGetEventProfilingInfo.html
