### ISSUE TITLE
Add new DeviceReset Sysman API for supporting FLR based reset

### ISSUE THREAD

**Issue by saik-intel** [oneapi-src/level-zero-spec#58]
Current DeviceReset API (zesDeviceReset) talk about device reset which in linux we are doing warm reset and user might be interested to do device reset for the following

FLR based reset
Warm reset
Cold Reset
need new API to support DeviceReset specifying the flag which reset user would like to have

**Comment by wdamon-intel** [comment]
@saik-intel suggested adding a new API to provide support:

`ze_result_t zesDeviceResetExt(zes_device_handle_t hDevice, ze_bool_t force, ze_device_reset_type_t reset_type);`

**Comment by wdamon-intel** [comment]
PR #134

**Comment by wdamon-intel** [comment]
Closed with PR #134
