### ISSUE TITLE
Define layout for ze_ipc_mem_handle_t?

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/level-zero-spec#68]
ze_ipc_mem_handle_t is defined as an opaque data. however, drivers like L0 GPU driver, have a specific layout that applications might need to be aware of. For instance, applications might need to know:

- does ze_ipc_mem_handle_t contain only the dma-buf file descriptor in case of linux?
- can I zero the ze_ipc_mem_handle_t and copy the fd, or is there any data inside that needs to be kept that has been previously set by the driver?

So the question is: should we define a layout for ze_ipc_mem_handle_t? One example could be:

char data[ZE_MAX_IPC_HANDLE_SIZE][¶](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=ipc#_CPPv4N19ze_ipc_mem_handle_t4dataE)

ZE_MAX_IPC_HANDLE_SIZE is 64B:

0 - 7: file descriptor
8: memory type
9 - 63: reserved

same could apply for ze_ipc_event_pool_handle_t, which drivers could use to encode other information:
0 - 7: file descriptor
8: num of events
9: flags
10:  reserved

However, another point of view could be: should we define this in the spec, or should we leave driver implementations to define that layout?

**Comment by MichalMrozek** [comment]
why we cannot have it as opaque data?
Relying on specific driver implementation details is highly error prone and prevents any driver changes.

**Comment by jandres742** [comment]
@MichalMrozek because applications may need that information.
For instance, for IPC memory: it is not opaque if L0 driver implementation is using a dma-buf handle. Applications need to know a dma-buf handle is used, need to extract it from the IPC handle, and pass it using specific Linux mechanisms, given dma-buf security restrictions.

So valid questions are: where the dma-buf handle is in the 64B of IPC handle's  data[ZE_MAX_IPC_HANDLE_SIZE], at the beginning? the end? is there any other information in that handle that the driver is passing between processes (L0 GPU driver is doing that). and of course, at the moment we say where the dma-buf fd is in the data array, it is not opaque anymore.

but again, maybe all this is very specific to L0 GPU driver implementation, and not needed in the spec, and if an L0 driver implementation needs applications to know how the IPC handle layout, then such documentation should be in the L0 driver implementation, not the spec.

**Comment by MichalMrozek** [comment]
On Kernels 5.6 or greater Level Zero can do :

zeMemGetIpcHandle

call PrimeHandleToFd
set FD in ze_ipc_mem_handle_t
set process id in ze_ipc_mem_handle_t as well
Applications passes ze_ipc_mem_handle_t as opaque structure, it copies all the contents

zeMemOpenIpcHandle

receives FD from other process identified by PID
calls https://man7.org/linux/man-pages/man2/pidfd_getfd.2.html to have valid FD in current process
opens it in the current process and proceeds.

On older Kernels, this functionality may be marked as unavailable via caps, or the driver may do socket exchange as described here:
https://copyconstruct.medium.com/file-descriptor-transfer-over-unix-domain-sockets-dcbbf5b3b6ec


So Level Zero has ways to make ze_ipc_mem_handle_t truly opaque.

**Comment by zzdanowicz** [comment]
I would like to point out that definitions of memory layout is usually attributed to network packets or frames. GPU APIs rather go with "get property" or "do operation" API functions.

**Comment by jandres742** [comment]
From talking with customers, a request came to have utility functions to get the file descriptor out of an IPC handle, and vice-versa. This would allow applications to be able to use the opaque handle w/o needing to know the internal layout of the opaque handle, and to be able to intermix  IPC opaque APIs (zeMemGetIpcHandle, zeMemOpenIpcHandle, etc) with
explicit file descriptor APIs (e.g., ze_external_memory_export_fd_t).

Proposal in https://github.com/oneapi-src/level-zero-spec/pull/105

**Comment by pboudier09** [comment]
> Applications need to know a dma-buf handle is used, need to extract it from the IPC handle, and pass it using specific Linux mechanisms, given dma-buf security restrictions.

instead of exposing the internal dma-buf, could we hide the functionality in level0 that the applications have to implement ?
(so the driver hides the different implementations for different kernels, and can make changes without breaking applications)

**Comment by jandres742** [comment]
@pboudier09 : L0 is already (at least trying) to hide the functionality that applications have to implement. Are there issues you think we are still missing to do so?

**Comment by zzdanowicz** [comment]
@jandres742  I think we miss IPC event pools: https://github.com/oneapi-src/level-zero-spec/issues/205

**Comment by jandres742** [comment]
> @jandres742 I think we miss IPC event pools: #205

ah ok ,that is correct @zzdanowicz . we will add that next.
