### ISSUE TITLE
Module build option clarification

### ISSUE THREAD

**Issue by wdamon-intel** [oneapi-src/level-zero-spec#76]
The spec does not describe how to handle the `-ze-opt-large-register-file` option if/when the large GRF mode is *not* supported. Language should be added to describe this condition and define the expected result.

**Comment by jandres742** [comment]
thanks @wdamon-intel . Basically I think we have two options when a build option is not supported by target driver:

Ignore:
-	Good for portability, as users don’t need to change code to run on different Gens.
-       And emit Warning.

Emit error:
-	Good to alert user something is wrong
