### ISSUE TITLE
Add zeMemPutIpcHandle()

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/level-zero-spec#89]
L0 has zeMemGetIpcHandle to obtain the IPC handle for a given allocation. This IPC handle in the exporter is only closed when calling zeMemFree.

This produces a problem, if an IPC handle refers to a file descriptor, which is a finite resource in the system, since if the application wants to reduce the count of file descriptors opened, would have to deallocate the allocation altogether.

So idea here is to have a complementary call zeMemPutIpcHandle, with which application can tell L0 driver that is done with the handle, w/o needing to free the allocation.

We would have then

on the exporter:
zeMemAlloc
zeMemGetIpcHandle
zeMemPutIpcHandle
zeMemFree

and in the importer
zeMemOpenIpcHandle
zeMemCloseIpcHandle

**Comment by wdamon-intel** [comment]
> why it is called zeMemPutIpcHandle. It should rather have something with "release" in name. "Put indicates that we put it somewhere". Can we change name to "zeMemReleaseIpcHandle" ?

This one is interesting because the way the handle is obtained is with `Get`, not `Alloc` or `Create`. We might propose a different naming to obtain the handle and coincide the 'release' nomenclature to match?

**Comment by MichalMrozek** [comment]
We already have "get" API, so I wouldn't change that.
For me opposite of getting something is releasing it.

**Comment by wdamon-intel** [comment]
> opposite of getting something is releasing it.

Having `get` in the name of an interface generally implies that the user wishes to obtain an unowned reference. In older platform code, get/put align as malloc/free or create/release, so I can see the relationship.

**Comment by jandres742** [comment]
@MichalMrozek :
@wdamon-intel  is correct,`Put` is more akin to network terminology,

**Comment by MichalMrozek** [comment]
ok, no objections then from my side.

**Comment by wdamon-intel** [comment]
Fixed with #91
