### ISSUE TITLE
Please add new API to synchronize immediate command lists with host

### ISSUE THREAD

**Issue by MichalMrozek** [oneapi-src/level-zero-spec#93]
For non immediate command lists, user can call zeCommandQueueSynchronize.
For immediate command list, the only way to achieve the same is to submit a barrier returning event and waiting on it.
Submitting barrier has an associated cost, driver can optimize waiting by inspecting the state of immediate command list to see if any submission is necessary.

Proposed API
ze_result_t zeImmediateCommandListHostSynchronize(hCommandList, uint64_t timeout)

**Comment by jandres742** [comment]
Related: https://github.com/oneapi-src/level-zero-spec/issues/81

**Comment by jandres742** [comment]
so the value of this API is that application won't have to track all events associated with previously-submitted commands to the immediate list, to know if all commands have completed. Instead, they could use this API.

So does something like this look correct @MichalMrozek ?
```cpp
///////////////////////////////////////////////////////////////////////////////
/// @brief Synchronizes an immediate command list by waiting on the host.
/// 
/// @details
///     - The application must call this function only with command lists created with zeCommandListCreateImmediate
///     - Waits for the completion of all commands previously submitted to the immediate command list.
///     - The application may call this function from simultaneous threads.
///     - The implementation of this function should be lock-free.
/// 
/// @returns
///     - ::ZE_RESULT_SUCCESS
///     - ::ZE_RESULT_ERROR_UNINITIALIZED
///     - ::ZE_RESULT_ERROR_DEVICE_LOST
///     - ::ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY
///     - ::ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY
///     - ::ZE_RESULT_ERROR_INVALID_ARGUMENT
///         + hCommandList does not correspond to an immediate command list
///     - ::ZE_RESULT_ERROR_INVALID_NULL_HANDLE
///         + `nullptr == hCommandQueue`
///     - ::ZE_RESULT_NOT_READY
///         + timeout expired
ZE_APIEXPORT ze_result_t ZE_APICALL
zeCommandListHostSynchronize(
    ze_command_list_handle_t hCommandList,          ///< [in] handle of the command list
    uint64_t timeout                                ///< [in] if non-zero, then indicates the maximum time (in nanoseconds) to
                                                    ///< yield before returning ::ZE_RESULT_SUCCESS or ::ZE_RESULT_NOT_READY;
                                                    ///< if zero, then immediately returns the status of the command list;
                                                    ///< if UINT64_MAX, then function will not return until complete or device
                                                    ///< is lost.
                                                    ///< Due to external dependencies, timeout may be rounded to the closest
                                                    ///< value allowed by the accuracy of those dependencies.
    );
```

**Comment by MichalMrozek** [comment]
lgtm

**Comment by aravindksg** [comment]
`ZE_APIEXPORT ze_result_t ZE_APICALL zeCommandListHostSynchronize()` -> `zeCommandListImmediateSynchronize()`?

**Comment by rdeodhar** [comment]
The sync should be limited to that immediate commandlist, i.e. no side-effects on submissions to other immediate commandlists.

**Comment by jandres742** [comment]
> `ZE_APIEXPORT ze_result_t ZE_APICALL zeCommandListHostSynchronize()` -> `zeCommandListImmediateSynchronize()`?

If we dont add the "Host", it is not explicitly stated where the wait is being performed, is it in the host or in the GPU? The host makes it clearer.

**Comment by aravindksg** [comment]
> The host makes it clearer.

sure this is matter of semantics I guess. I added "immediate" wording to make it clear that we need this just for immediate cmdlists. for regular cmdlist, we already have `zeCommandQueueSynchronize` (note that we don't have "Host" wording for `zeCommandQueueSynchronize` ;) )

**Comment by jandres742** [comment]
PR in https://github.com/oneapi-src/level-zero-spec/pull/103
