### ISSUE TITLE
Clarify immediate command lists usage - forbid executing immediate command lists with zeCommandQueueExecuteCommandLists()

### ISSUE THREAD

**Issue by HoppeMateusz** [oneapi-src/level-zero-spec#98]
Spec does not forbid passing immediate cmd lists to zeCommandQueueExecuteCommandLists().

it also allows closing and resetting imm cmd lists - which may suggest imm cmd lists, once encoded, can be executed multiple times:

> An immediate command list is not required to be closed or reset. However, usage will be honored, and expected behaviors will be followed.

If immediate command lists do not keep state  ( appended kernels/copies ) they should not be allowed to be executed multiple times on command queues and spec should explicitly state that.

**Comment by jandres742** [comment]
thanks @HoppeMateusz . 

> An immediate command list is not required to be closed or reset. However, usage will be honored, and expected behaviors will be followed.

The way I read that is that reset or closed is not needed, and if called, driver implementation could just do a NOP if it wants.

Spec doesnt explicitly says that zeCommandQueueExecuteCommandLists shouldn't be used with immediate command lists, but maybe we add that to the spec.

**Comment by HoppeMateusz** [comment]
i would add this restriction to: 
 https://spec.oneapi.io/level-zero/latest/core/api.html#zecommandlistcreateimmediate
and to :
 https://spec.oneapi.io/level-zero/latest/core/api.html#zecommandqueueexecutecommandlists 

stating that immediate command list handle must not be used with zeCommandQueueExecuteCommandLists()
